image: ubuntu

version: '0.1.{build}'

stack:
- python 3.12

install:
- source .ci/update_build_version.sh
- python --version
- python -m ensurepip --upgrade
- pip3 install --upgrade tomlkit pyyaml
- curl -LsSf https://astral.sh/uv/install.sh | sh
- export PATH=$HOME/.local/bin:$PATH

build_script:
- python .ci/patch_toml_version.py pyproject.toml $PYPI_VER
- python .ci/patch_pubspec_version.py src/flutter/flet_video/pubspec.yaml $PKG_VER
- uv build

artifacts:
- path: dist/*.whl

test: off